export const queryKeys = {
  session: ['session'] as const,
  dashboard: (month: number, year: number) => ['dashboard', month, year] as const,
  reservas: ['reservas'] as const,
  movimentacoes: (reservaId: number) => ['movimentacoes', reservaId] as const,
  categorias: ['categorias'] as const,
  cartoes: ['cartoes'] as const,
  perfis: ['perfis'] as const,
  representantes: ['representantes'] as const,
  socios: ['socios'] as const,
  avaliacoes: ['avaliacoes'] as const,
  incomeTypes: ['income-types'] as const,
  mesStatus: (year: number, month: number) => ['mes-status', year, month] as const,
  clientes: ['clientes'] as const,
  contratos: (clienteId: number) => ['contratos', clienteId] as const,
  servicos: ['servicos'] as const,
  contratosServicos: (contratoId: number) => ['contratos-servicos', contratoId] as const,
  contratoAnexos: (contratoId: number) => ['contrato-anexos', contratoId] as const,
  contratosAtivos: ['contratos-ativos'] as const,
  contratosStatusFaturamento: (mes: number, ano: number) => ['contratos-status-faturamento', mes, ano] as const,
  dashboardAnual: (year: number) => ['dashboard-anual', year] as const,
  parcelasFuturas: (mes: number, ano: number, meses: number) => ['parcelas-futuras', mes, ano, meses] as const,
};
